version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - enid_service_network
    
networks:
  enid_service_network:
    external: true
